twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        sitename: '%env(SITENAME)%'
        analytics_id: '%env(ANALYTICS_ID)%'
    form_themes: ['bootstrap_4_layout.html.twig']

