language: php
services:
    - mysql
php:
  - '5.6'
  - '7.0'

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
install:
    - bin/reset
script:
    - bin/phpunit
