# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    providers:
        in_memory:
            memory:
                users:
                    admin: {password: "%admin_password%", roles: ['ROLE_ADMIN'] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            logout_on_user_change: true
            security: false

        admin:
            pattern: ^/admin
            logout_on_user_change: true
            http_basic:
                realm: "Zone sécurisé"

        main:
            logout_on_user_change: true
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
