# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    twig.currency:
        class: AppBundle\Price\Twig\PriceExtension
        tags:
            - { name: twig.extension, alias: price }

    twig.photo:
        class: AppBundle\Twig\PhotoExtension
        arguments: [ '@photo_service' ]
        tags:
            - { name: twig.extension, alias: photo }

    twig.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension, alias: intl }

    planning:
        class: AppBundle\Service\Planning
        arguments: [ "@doctrine.orm.default_entity_manager" ]

    photo_service:
        class: AppBundle\Service\PhotoService
        arguments: [ "%kernel.root_dir%/../web/uploads", "/uploads" ]

    form.type.order:
        class: AppBundle\Form\Type\OrderType
        arguments: [ "@planning" ]
        tags:
            - { name: form.type }

    form.type.meal:
        class: AppBundle\Form\Type\MealType
        arguments: [ "@photo_service" ]
        tags:
            - { name: form.type }

    notification:
        class: AppBundle\Service\Notification
        arguments: [ "@twig", "@mailer", "%owner_recipient%", "%mailer_sender%" ]
        tags:
            - { name: kernel.event_subscriber }
