# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    twig.currency:
        class: AppBundle\Price\Twig\PriceExtension
        tags:
            - { name: twig.extension, alias: price }

    twig.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension, alias: intl }

    planning:
        class: AppBundle\Service\Planning
        arguments: [ "@doctrine.orm.default_entity_manager" ]

    form.type.order:
        class: AppBundle\Form\Type\OrderType
        arguments: [ "@planning" ]
        tags:
            - { name: form.type }
